name: eksworkflow
on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  cicd_job:
    name: build and deploy to eks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Configure temporary AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::416338226474:role/GithubAction-Role
        role-session-name: github-actions-${{ github.run_id }}

    - name: Confirm AWS account
      run: aws sts get-caller-identity

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: build,tag,push docker image to ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: myapps/pacman
        IMAGE_TAG: ${{ github.sha }}
          
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./docker
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Connect to EKS
      run: aws eks update-kubeconfig --region us-west-2 --name PacmanCluster
