name: eksworkflow
#on:
 # push:
  #  branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  cicd_job:
    name: build and deploy to eks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Configure temporary AWS credentials with OIDC
      uses: aws-actions/configure-aws-credentials@v6.1.0
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::380648615517:role/GithubAction-Role
        role-session-name: github-actions-${{ github.run_id }}

    - name: Confirm AWS account
      run: aws sts get-caller-identity

    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: build,tag,push docker image to ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: pacman
        IMAGE_TAG: ${{ github.sha }}
          
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./docker
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update Kubernetes image tag
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        sed -i "s|IMAGE_TAG_PLACEHOLDER|$IMAGE_TAG|g" ./k8s/app_deployment.yaml
    
    - name: Connect to EKS
      run: aws eks update-kubeconfig --region us-west-2 --name auto-mode-cluster

    - name: Deploy to EKS
      run: |
        kubectl apply -f ./k8s/storage_class.yaml
        kubectl apply -f ./k8s/db_sts.yaml
        kubectl apply -f ./k8s/app_deployment.yaml

        kubectl rollout status statefulset mongo
        kubectl rollout status deployment pacman-deployment
        kubectl get svc
